name: push-docker-to-aliyun

on:
  workflow_dispatch:
    inputs:
      docker_image:
        description: 'Docker image to pull and push to Aliyun registry'
        required: true
        default: 'nginx:latest'


env:
  ALIYUN_REGISTRY: "${{ secrets.ALIYUN_REGISTRY }}"
  ALIYUN_NAME_SPACE: "${{ secrets.ALIYUN_NAME_SPACE }}"
  ALIYUN_REGISTRY_USER: "${{ secrets.ALIYUN_REGISTRY_USER }}"
  ALIYUN_REGISTRY_PASSWORD: "${{ secrets.ALIYUN_REGISTRY_PASSWORD }}"

jobs:

  build:
    name: Pull
    runs-on: ubuntu-latest
    steps:
    - name: Before freeing up disk space
      run: |
        echo "Before freeing up disk space"
        echo "=============================================================================="
        df -hT
        echo "=============================================================================="

    # 增加可用磁盘空间
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:

        root-reserve-mb: 2048
        swap-size-mb: 128
        remove-dotnet: 'true'
        remove-haskell: 'true'
        # 如果空间还是不够用，可以把以下开启，清理出更多空间
        # remove-android: 'true'
        # remove-codeql: 'true'
        build-mount-path: '/var/lib/docker/'

    - name: Restart docker
      run: sudo service docker restart

    - name: Free up disk space complete
      run: |
        echo "Free up disk space complete"
        echo "=============================================================================="
        df -hT
        echo "=============================================================================="

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3

    - name: login Aliyun
      run: docker login -u $ALIYUN_REGISTRY_USER -p $ALIYUN_REGISTRY_PASSWORD $ALIYUN_REGISTRY

    - name: Pull Docker Image
      run: docker pull ${{ github.event.inputs.docker_image }}

    - name: tag image
      run: |
        image_name_tag="$ALIYUN_REGISTRY/$ALIYUN_NAME_SPACE/${{ github.event.inputs.docker_image }}"
        docker tag ${{ github.event.inputs.docker_image }} $image_name_tag


    - name: build and push image to Aliyun registry
      run: |
        echo "构建镜像 tag"
        image_name_tag="$ALIYUN_REGISTRY/$ALIYUN_NAME_SPACE/${{ github.event.inputs.docker_image }}"
        docker tag ${{ github.event.inputs.docker_image }} $image_name_tag
        
        echo "开始推送镜像到阿里云"
        docker push $image_name_tag
        docker login -u $ALIYUN_REGISTRY_USER -p $ALIYUN_REGISTRY_PASSWORD $ALIYUN_REGISTRY
        
        echo "开始清理磁盘空间"
        echo "=============================================================================="
        df -hT
        echo "=============================================================================="
        docker rmi ${{ github.event.inputs.docker_image }}
        docker rmi $image_name_tag
        echo "磁盘空间清理完毕"
        echo "=============================================================================="
        df -hT
        echo "=============================================================================="
            

